name: Deploy-Android-main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
env:
  APP_CENTER_TOKEN: $APP_CENTER_TOKEN_ANDROID_TEST
  APP_NAME: $MyApp-Android/simple_react_native_app_prod  
  UPLOAD_FILE: $android/app/build/outputs/apk/app-release.apk  
  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Install dependencies
        run: npm install

      - name: Build android
        run: npm run && cd android && ./gradlew assembleRelease

      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: $
          token: $
          group: $
          file: $
          notifyTesters: true
          debug: false
